// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelTracking.Data;

#nullable disable

namespace ParcelTracking.Migrations
{
    [DbContext(typeof(ParcelDbContext))]
    [Migration("20251007171723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ParcelTracking.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parcels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eta = new DateTime(2025, 10, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney Facility",
                            Status = "Dispatched",
                            TrackingNumber = "AP100001"
                        },
                        new
                        {
                            Id = 2,
                            Eta = new DateTime(2025, 10, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney Hub",
                            Status = "In Transit",
                            TrackingNumber = "AP100002"
                        },
                        new
                        {
                            Id = 3,
                            Eta = new DateTime(2025, 10, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney Hub",
                            Status = "Processed",
                            TrackingNumber = "AP100003"
                        },
                        new
                        {
                            Id = 4,
                            Eta = new DateTime(2025, 10, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Wollongong Depot",
                            Status = "Out for Delivery",
                            TrackingNumber = "AP100004"
                        },
                        new
                        {
                            Id = 5,
                            Eta = new DateTime(2025, 10, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Wollongong",
                            Status = "Delivered",
                            TrackingNumber = "AP100005"
                        },
                        new
                        {
                            Id = 6,
                            Eta = new DateTime(2025, 10, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Melbourne Hub",
                            Status = "Delayed",
                            TrackingNumber = "AP100006"
                        },
                        new
                        {
                            Id = 7,
                            Eta = new DateTime(2025, 10, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney Airport",
                            Status = "Held at Customs",
                            TrackingNumber = "AP100007"
                        },
                        new
                        {
                            Id = 8,
                            Eta = new DateTime(2025, 10, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Canberra Facility",
                            Status = "In Transit",
                            TrackingNumber = "AP100008"
                        },
                        new
                        {
                            Id = 9,
                            Eta = new DateTime(2025, 10, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Brisbane Hub",
                            Status = "Processed",
                            TrackingNumber = "AP100009"
                        },
                        new
                        {
                            Id = 10,
                            Eta = new DateTime(2025, 10, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Canberra Depot",
                            Status = "Out for Delivery",
                            TrackingNumber = "AP100010"
                        },
                        new
                        {
                            Id = 11,
                            Eta = new DateTime(2025, 10, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Canberra",
                            Status = "Delivered",
                            TrackingNumber = "AP100011"
                        },
                        new
                        {
                            Id = 12,
                            Eta = new DateTime(2025, 10, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Perth Hub",
                            Status = "Processing",
                            TrackingNumber = "AP100012"
                        },
                        new
                        {
                            Id = 13,
                            Eta = new DateTime(2025, 10, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Adelaide Hub",
                            Status = "In Transit",
                            TrackingNumber = "AP100013"
                        },
                        new
                        {
                            Id = 14,
                            Eta = new DateTime(2025, 10, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Adelaide Hub",
                            Status = "Processed",
                            TrackingNumber = "AP100014"
                        },
                        new
                        {
                            Id = 15,
                            Eta = new DateTime(2025, 10, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Darwin Hub",
                            Status = "Delayed",
                            TrackingNumber = "AP100015"
                        },
                        new
                        {
                            Id = 16,
                            Eta = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Melbourne Facility",
                            Status = "Dispatched",
                            TrackingNumber = "AP100016"
                        },
                        new
                        {
                            Id = 17,
                            Eta = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney Depot",
                            Status = "Out for Delivery",
                            TrackingNumber = "AP100017"
                        },
                        new
                        {
                            Id = 18,
                            Eta = new DateTime(2025, 10, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney",
                            Status = "Delivered",
                            TrackingNumber = "AP100018"
                        },
                        new
                        {
                            Id = 19,
                            Eta = new DateTime(2025, 10, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Hobart Hub",
                            Status = "Processing",
                            TrackingNumber = "AP100019"
                        },
                        new
                        {
                            Id = 20,
                            Eta = new DateTime(2025, 10, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Gold Coast Hub",
                            Status = "In Transit",
                            TrackingNumber = "AP100020"
                        },
                        new
                        {
                            Id = 21,
                            Eta = new DateTime(2025, 10, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Gold Coast Hub",
                            Status = "Processed",
                            TrackingNumber = "AP100021"
                        },
                        new
                        {
                            Id = 22,
                            Eta = new DateTime(2025, 10, 8, 17, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Melbourne Depot",
                            Status = "Out for Delivery",
                            TrackingNumber = "AP100022"
                        },
                        new
                        {
                            Id = 23,
                            Eta = new DateTime(2025, 10, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Melbourne",
                            Status = "Delivered",
                            TrackingNumber = "AP100023"
                        },
                        new
                        {
                            Id = 24,
                            Eta = new DateTime(2025, 10, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Perth Facility",
                            Status = "Held at Facility",
                            TrackingNumber = "AP100024"
                        },
                        new
                        {
                            Id = 25,
                            Eta = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney Hub",
                            Status = "In Transit",
                            TrackingNumber = "AP100025"
                        },
                        new
                        {
                            Id = 26,
                            Eta = new DateTime(2025, 10, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Sydney Hub",
                            Status = "Processed",
                            TrackingNumber = "AP100026"
                        },
                        new
                        {
                            Id = 27,
                            Eta = new DateTime(2025, 10, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Canberra Hub",
                            Status = "Delayed",
                            TrackingNumber = "AP100027"
                        },
                        new
                        {
                            Id = 28,
                            Eta = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Brisbane Hub",
                            Status = "Processing",
                            TrackingNumber = "AP100028"
                        },
                        new
                        {
                            Id = 29,
                            Eta = new DateTime(2025, 10, 8, 20, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Brisbane Depot",
                            Status = "Out for Delivery",
                            TrackingNumber = "AP100029"
                        },
                        new
                        {
                            Id = 30,
                            Eta = new DateTime(2025, 10, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            History = "[]",
                            Location = "Brisbane",
                            Status = "Delivered",
                            TrackingNumber = "AP100030"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
