// <auto-generated />
using CourseSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseSearch.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20250928100723_Add_Data")]
    partial class Add_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CourseSearch.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseCode");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseCode = "IT101",
                            CourseArea = "Information Technology",
                            CourseName = "Intro to Programming",
                            Duration = "6 months",
                            EstimatedFee = 2500m,
                            Level = "Certificate IV",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT201",
                            CourseArea = "Information Technology",
                            CourseName = "Web Development Bootcamp",
                            Duration = "9 months",
                            EstimatedFee = 6000m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "IT301",
                            CourseArea = "Information Technology",
                            CourseName = "Cloud Computing Fundamentals",
                            Duration = "6 months",
                            EstimatedFee = 4800m,
                            Level = "Graduate Certificate",
                            Location = "Brisbane",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "IT401",
                            CourseArea = "Information Technology",
                            CourseName = "Data Science and Machine Learning",
                            Duration = "18 months",
                            EstimatedFee = 15000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT501",
                            CourseArea = "Information Technology",
                            CourseName = "Cyber Security Essentials",
                            Duration = "12 months",
                            EstimatedFee = 7500m,
                            Level = "Diploma",
                            Location = "Wollongong",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT100",
                            CourseArea = "Health",
                            CourseName = "Certificate III in Individual Support",
                            Duration = "12 months",
                            EstimatedFee = 4500m,
                            Level = "Certificate III",
                            Location = "Wollongong",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT200",
                            CourseArea = "Health",
                            CourseName = "Diploma of Nursing",
                            Duration = "18 months",
                            EstimatedFee = 12000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT300",
                            CourseArea = "Health",
                            CourseName = "Community Health Worker Training",
                            Duration = "9 months",
                            EstimatedFee = 5200m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT400",
                            CourseArea = "Health",
                            CourseName = "Mental Health Support",
                            Duration = "6 months",
                            EstimatedFee = 5000m,
                            Level = "Graduate Certificate",
                            Location = "Adelaide",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "HLT500",
                            CourseArea = "Health",
                            CourseName = "Public Health Policy",
                            Duration = "24 months",
                            EstimatedFee = 16000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD10",
                            CourseArea = "Trades",
                            CourseName = "Basic Carpentry Skills",
                            Duration = "8 months",
                            EstimatedFee = 5000m,
                            Level = "Certificate II",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD20",
                            CourseArea = "Trades",
                            CourseName = "Electrical Apprenticeship",
                            Duration = "24 months",
                            EstimatedFee = 9000m,
                            Level = "Certificate III",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD30",
                            CourseArea = "Trades",
                            CourseName = "Plumbing Fundamentals",
                            Duration = "12 months",
                            EstimatedFee = 6000m,
                            Level = "Certificate II",
                            Location = "Adelaide",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "TRD40",
                            CourseArea = "Trades",
                            CourseName = "Welding and Fabrication",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Certificate IV",
                            Location = "Perth",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD50",
                            CourseArea = "Trades",
                            CourseName = "Advanced Automotive Mechanics",
                            Duration = "24 months",
                            EstimatedFee = 14000m,
                            Level = "Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP01",
                            CourseArea = "Hospitality",
                            CourseName = "Commercial Cookery",
                            Duration = "12 months",
                            EstimatedFee = 7000m,
                            Level = "Certificate IV",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP02",
                            CourseArea = "Hospitality",
                            CourseName = "Diploma of Hotel Management",
                            Duration = "18 months",
                            EstimatedFee = 12000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HOSP03",
                            CourseArea = "Hospitality",
                            CourseName = "Certificate III in Bakery",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate III",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP04",
                            CourseArea = "Hospitality",
                            CourseName = "Barista and Café Management",
                            Duration = "6 months",
                            EstimatedFee = 2800m,
                            Level = "Certificate II",
                            Location = "Wollongong",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "HOSP05",
                            CourseArea = "Hospitality",
                            CourseName = "Advanced Culinary Arts",
                            Duration = "9 months",
                            EstimatedFee = 9500m,
                            Level = "Graduate Certificate",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA1",
                            CourseArea = "Creative Arts",
                            CourseName = "Introduction to Fashion Design",
                            Duration = "6 months",
                            EstimatedFee = 3000m,
                            Level = "Certificate II",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "CREA2",
                            CourseArea = "Creative Arts",
                            CourseName = "Diploma of Interior Design",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA3",
                            CourseArea = "Creative Arts",
                            CourseName = "Certificate IV in Photography",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate IV",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA4",
                            CourseArea = "Creative Arts",
                            CourseName = "Bachelor of Fine Arts",
                            Duration = "36 months",
                            EstimatedFee = 28000m,
                            Level = "Bachelor",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA5",
                            CourseArea = "Creative Arts",
                            CourseName = "Certificate III in Graphic Design",
                            Duration = "9 months",
                            EstimatedFee = 4000m,
                            Level = "Certificate III",
                            Location = "Canberra",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "BUS101",
                            CourseArea = "Business and Administration",
                            CourseName = "Business Administration Basics",
                            Duration = "6 months",
                            EstimatedFee = 2000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "BUS201",
                            CourseArea = "Business and Administration",
                            CourseName = "Certificate IV in Leadership",
                            Duration = "12 months",
                            EstimatedFee = 4500m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "BUS301",
                            CourseArea = "Business and Administration",
                            CourseName = "Bachelor of Commerce",
                            Duration = "36 months",
                            EstimatedFee = 30000m,
                            Level = "Bachelor",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS401",
                            CourseArea = "Business and Administration",
                            CourseName = "Graduate Diploma in Project Management",
                            Duration = "12 months",
                            EstimatedFee = 12000m,
                            Level = "Graduate Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS501",
                            CourseArea = "Business and Administration",
                            CourseName = "Master of Business Administration",
                            Duration = "24 months",
                            EstimatedFee = 35000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG01",
                            CourseArea = "Agriculture",
                            CourseName = "Agricultural Practices",
                            Duration = "9 months",
                            EstimatedFee = 4200m,
                            Level = "Certificate III",
                            Location = "Regional NSW",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG02",
                            CourseArea = "Agriculture",
                            CourseName = "Certificate IV in Horticulture",
                            Duration = "12 months",
                            EstimatedFee = 5500m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "AG03",
                            CourseArea = "Agriculture",
                            CourseName = "Diploma of Agribusiness",
                            Duration = "18 months",
                            EstimatedFee = 9000m,
                            Level = "Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG04",
                            CourseArea = "Agriculture",
                            CourseName = "Bachelor of Agricultural Science",
                            Duration = "36 months",
                            EstimatedFee = 28000m,
                            Level = "Bachelor",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG05",
                            CourseArea = "Agriculture",
                            CourseName = "Sustainable Farming Practices",
                            Duration = "6 months",
                            EstimatedFee = 7000m,
                            Level = "Graduate Certificate",
                            Location = "Sydney",
                            StudyOption = "Self-paced"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
