// <auto-generated />
using CourseSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseSearch.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    partial class CourseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CourseSearch.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseCode");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseCode = "IT101",
                            CourseArea = "Information Technology",
                            CourseName = "Intro to Programming",
                            Duration = "6 months",
                            EstimatedFee = 2500m,
                            Level = "Certificate IV",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT102",
                            CourseArea = "Information Technology",
                            CourseName = "Hardware Technician Skill Set",
                            Duration = "3 months",
                            EstimatedFee = 1500m,
                            Level = "Statement of Attainment",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT103",
                            CourseArea = "Information Technology",
                            CourseName = "Applied Digital Technologies",
                            Duration = "12 months",
                            EstimatedFee = 4000m,
                            Level = "Master",
                            Location = "Wollongong",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "IT104",
                            CourseArea = "Information Technology",
                            CourseName = "Systems Administration Support",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT105",
                            CourseArea = "Information Technology",
                            CourseName = "Advanced Networking, Cloud Architecture",
                            Duration = "6 months",
                            EstimatedFee = 4000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT106",
                            CourseArea = "Information Technology",
                            CourseName = "Database and Data Management",
                            Duration = "6 months",
                            EstimatedFee = 4000m,
                            Level = "Diploma",
                            Location = "Perth",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT107",
                            CourseArea = "Information Technology",
                            CourseName = "Business Analysis",
                            Duration = "12 months",
                            EstimatedFee = 7500m,
                            Level = "Graduate Certificate",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT201",
                            CourseArea = "Information Technology",
                            CourseName = "Web Development Bootcamp",
                            Duration = "9 months",
                            EstimatedFee = 6000m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "IT202",
                            CourseArea = "Information Technology",
                            CourseName = "Web Development for Introductory Roles Skill Set",
                            Duration = "3 months",
                            EstimatedFee = 2000m,
                            Level = "Statement of Attainment",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT203",
                            CourseArea = "Information Technology",
                            CourseName = "Back End Web Development",
                            Duration = "12 months",
                            EstimatedFee = 4000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "IT204",
                            CourseArea = "Information Technology",
                            CourseName = "Front End Web Development",
                            Duration = "12 months",
                            EstimatedFee = 4000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "IT301",
                            CourseArea = "Information Technology",
                            CourseName = "Cloud Computing Fundamentals",
                            Duration = "6 months",
                            EstimatedFee = 4800m,
                            Level = "Graduate Certificate",
                            Location = "Brisbane",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "IT401",
                            CourseArea = "Information Technology",
                            CourseName = "Data Science and Machine Learning",
                            Duration = "18 months",
                            EstimatedFee = 15000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT402",
                            CourseArea = "Information Technology",
                            CourseName = "Computer Vision Algorithms",
                            Duration = "6 months",
                            EstimatedFee = 6000m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT403",
                            CourseArea = "Information Technology",
                            CourseName = "Big Data Management",
                            Duration = "12 months",
                            EstimatedFee = 12000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT404",
                            CourseArea = "Information Technology",
                            CourseName = "Natural Language Processing Systems",
                            Duration = "6 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate IV",
                            Location = "Wollongong",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT405",
                            CourseArea = "Information Technology",
                            CourseName = "Applied Data Science in Security",
                            Duration = "36 months",
                            EstimatedFee = 40000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT501",
                            CourseArea = "Information Technology",
                            CourseName = "Cyber Security Essentials",
                            Duration = "12 months",
                            EstimatedFee = 7500m,
                            Level = "Diploma",
                            Location = "Wollongong",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "IT502",
                            CourseArea = "Information Technology",
                            CourseName = "Digital Security and Privacy",
                            Duration = "18 months",
                            EstimatedFee = 16000m,
                            Level = "Graduate Certificate",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT503",
                            CourseArea = "Information Technology",
                            CourseName = "Cyber Security and Advanced Networking",
                            Duration = "12 months",
                            EstimatedFee = 9500m,
                            Level = "Certificate IV",
                            Location = "Wollongong",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "IT504",
                            CourseArea = "Information Technology",
                            CourseName = "Cryptography Fundamentals",
                            Duration = "12 months",
                            EstimatedFee = 7500m,
                            Level = "Diploma",
                            Location = "Wollongong",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "IT505",
                            CourseArea = "Information Technology",
                            CourseName = "Modern Cryptography",
                            Duration = "24 months",
                            EstimatedFee = 20000m,
                            Level = "Master",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT100",
                            CourseArea = "Health",
                            CourseName = "Individual Support",
                            Duration = "12 months",
                            EstimatedFee = 4500m,
                            Level = "Certificate III",
                            Location = "Wollongong",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT200",
                            CourseArea = "Health",
                            CourseName = "Nursing",
                            Duration = "18 months",
                            EstimatedFee = 12000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT300",
                            CourseArea = "Health",
                            CourseName = "Community Health Worker Training",
                            Duration = "9 months",
                            EstimatedFee = 5200m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT400",
                            CourseArea = "Health",
                            CourseName = "Mental Health Support",
                            Duration = "6 months",
                            EstimatedFee = 5000m,
                            Level = "Graduate Certificate",
                            Location = "Adelaide",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "HLT500",
                            CourseArea = "Health",
                            CourseName = "Public Health Policy",
                            Duration = "24 months",
                            EstimatedFee = 16000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT600",
                            CourseArea = "Health",
                            CourseName = "Audiometry",
                            Duration = "6 months",
                            EstimatedFee = 6000m,
                            Level = "Diploma",
                            Location = "Perth",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT700",
                            CourseArea = "Health",
                            CourseName = "Dental Assisting",
                            Duration = "12 months",
                            EstimatedFee = 12000m,
                            Level = "Certificate III",
                            Location = "Canberra",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT701",
                            CourseArea = "Health",
                            CourseName = "Dental Radiography",
                            Duration = "12 months",
                            EstimatedFee = 12000m,
                            Level = "Certificate IV",
                            Location = "Canberra",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT800",
                            CourseArea = "Health",
                            CourseName = "Allied Health Assistance",
                            Duration = "12 months",
                            EstimatedFee = 5200m,
                            Level = "Certificate IV",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT801",
                            CourseArea = "Health",
                            CourseName = "Paramedical Science",
                            Duration = "18 months",
                            EstimatedFee = 10500m,
                            Level = "Diploma",
                            Location = "Brisbane",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT802",
                            CourseArea = "Health",
                            CourseName = "Graduate Certificate in Mental Health Nursing",
                            Duration = "12 months",
                            EstimatedFee = 8000m,
                            Level = "Graduate Certificate",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT803",
                            CourseArea = "Health",
                            CourseName = "Advanced Pathology Collection",
                            Duration = "9 months",
                            EstimatedFee = 6200m,
                            Level = "Diploma",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT804",
                            CourseArea = "Health",
                            CourseName = "Midwifery Practice",
                            Duration = "24 months",
                            EstimatedFee = 20000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT805",
                            CourseArea = "Health",
                            CourseName = "Physiotherapy Rehabilitation Techniques",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Graduate Diploma",
                            Location = "Wollongong",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT806",
                            CourseArea = "Health",
                            CourseName = "Nutrition and Dietetics",
                            Duration = "12 months",
                            EstimatedFee = 7500m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT807",
                            CourseArea = "Health",
                            CourseName = "Public Health Epidemiology",
                            Duration = "24 months",
                            EstimatedFee = 17000m,
                            Level = "Master",
                            Location = "Brisbane",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT808",
                            CourseArea = "Health",
                            CourseName = "Graduate Certificate in Occupational Therapy",
                            Duration = "12 months",
                            EstimatedFee = 9500m,
                            Level = "Graduate Certificate",
                            Location = "Perth",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HLT809",
                            CourseArea = "Health",
                            CourseName = "Community Aged Care Support",
                            Duration = "9 months",
                            EstimatedFee = 4800m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT810",
                            CourseArea = "Health",
                            CourseName = "Speech Pathology Fundamentals",
                            Duration = "12 months",
                            EstimatedFee = 7800m,
                            Level = "Diploma",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HLT811",
                            CourseArea = "Health",
                            CourseName = "Healthcare Management",
                            Duration = "18 months",
                            EstimatedFee = 12000m,
                            Level = "Graduate Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD10",
                            CourseArea = "Trades",
                            CourseName = "Basic Carpentry Skills",
                            Duration = "8 months",
                            EstimatedFee = 5000m,
                            Level = "Certificate II",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD20",
                            CourseArea = "Trades",
                            CourseName = "Electrical Apprenticeship",
                            Duration = "24 months",
                            EstimatedFee = 9000m,
                            Level = "Certificate III",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD30",
                            CourseArea = "Trades",
                            CourseName = "Plumbing Fundamentals",
                            Duration = "12 months",
                            EstimatedFee = 6000m,
                            Level = "Certificate II",
                            Location = "Adelaide",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "TRD40",
                            CourseArea = "Trades",
                            CourseName = "Welding and Fabrication",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Certificate IV",
                            Location = "Perth",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD50",
                            CourseArea = "Trades",
                            CourseName = "Advanced Automotive Mechanics",
                            Duration = "24 months",
                            EstimatedFee = 14000m,
                            Level = "Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD60",
                            CourseArea = "Trades",
                            CourseName = "Advanced Bricklaying",
                            Duration = "12 months",
                            EstimatedFee = 7000m,
                            Level = "Certificate III",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD61",
                            CourseArea = "Trades",
                            CourseName = "Building and Construction",
                            Duration = "18 months",
                            EstimatedFee = 9500m,
                            Level = "Certificate IV",
                            Location = "Brisbane",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "TRD62",
                            CourseArea = "Trades",
                            CourseName = "Automotive Electrical Technology",
                            Duration = "24 months",
                            EstimatedFee = 12000m,
                            Level = "Certificate III",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD63",
                            CourseArea = "Trades",
                            CourseName = "Painting and Decorating",
                            Duration = "12 months",
                            EstimatedFee = 6000m,
                            Level = "Certificate III",
                            Location = "Adelaide",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "TRD64",
                            CourseArea = "Trades",
                            CourseName = "Advanced Metal Fabrication",
                            Duration = "18 months",
                            EstimatedFee = 13500m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD65",
                            CourseArea = "Trades",
                            CourseName = "Refrigeration and Air Conditioning",
                            Duration = "24 months",
                            EstimatedFee = 14000m,
                            Level = "Certificate IV",
                            Location = "Perth",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD66",
                            CourseArea = "Trades",
                            CourseName = "Joinery",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate III",
                            Location = "Wollongong",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "TRD67",
                            CourseArea = "Trades",
                            CourseName = "Engineering Trades",
                            Duration = "24 months",
                            EstimatedFee = 14500m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "TRD68",
                            CourseArea = "Trades",
                            CourseName = "Advanced Electrical Control Systems",
                            Duration = "12 months",
                            EstimatedFee = 8000m,
                            Level = "Graduate Certificate",
                            Location = "Canberra",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "TRD69",
                            CourseArea = "Trades",
                            CourseName = "Automotive Air Conditioning",
                            Duration = "6 months",
                            EstimatedFee = 4000m,
                            Level = "Certificate II",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP01",
                            CourseArea = "Hospitality",
                            CourseName = "Commercial Cookery",
                            Duration = "12 months",
                            EstimatedFee = 7000m,
                            Level = "Certificate IV",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP02",
                            CourseArea = "Hospitality",
                            CourseName = "Hotel Management",
                            Duration = "18 months",
                            EstimatedFee = 12000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HOSP03",
                            CourseArea = "Hospitality",
                            CourseName = "Bakery",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate III",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP04",
                            CourseArea = "Hospitality",
                            CourseName = "Barista and Café Management",
                            Duration = "6 months",
                            EstimatedFee = 2800m,
                            Level = "Certificate II",
                            Location = "Wollongong",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "HOSP05",
                            CourseArea = "Hospitality",
                            CourseName = "Advanced Culinary Arts",
                            Duration = "9 months",
                            EstimatedFee = 9500m,
                            Level = "Graduate Certificate",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP06",
                            CourseArea = "Hospitality",
                            CourseName = "Event Management Essentials",
                            Duration = "12 months",
                            EstimatedFee = 8500m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP07",
                            CourseArea = "Hospitality",
                            CourseName = "Patisserie",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate III",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP08",
                            CourseArea = "Hospitality",
                            CourseName = "Advanced Wine and Beverage Studies",
                            Duration = "12 months",
                            EstimatedFee = 7200m,
                            Level = "Graduate Certificate",
                            Location = "Adelaide",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HOSP09",
                            CourseArea = "Hospitality",
                            CourseName = "Hospitality Management",
                            Duration = "18 months",
                            EstimatedFee = 9800m,
                            Level = "Certificate IV",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP10",
                            CourseArea = "Hospitality",
                            CourseName = "Hotel Operations and Guest Services",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HOSP11",
                            CourseArea = "Hospitality",
                            CourseName = "Bar Management",
                            Duration = "12 months",
                            EstimatedFee = 6200m,
                            Level = "Certificate IV",
                            Location = "Perth",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP12",
                            CourseArea = "Hospitality",
                            CourseName = "Restaurant Entrepreneurship",
                            Duration = "18 months",
                            EstimatedFee = 12500m,
                            Level = "Graduate Diploma",
                            Location = "Canberra",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "HOSP13",
                            CourseArea = "Hospitality",
                            CourseName = "Food and Beverage",
                            Duration = "6 months",
                            EstimatedFee = 3000m,
                            Level = "Certificate II",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP14",
                            CourseArea = "Hospitality",
                            CourseName = "Travel and Tourism Management",
                            Duration = "12 months",
                            EstimatedFee = 9000m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "HOSP15",
                            CourseArea = "Hospitality",
                            CourseName = "Advanced Catering Services",
                            Duration = "12 months",
                            EstimatedFee = 7000m,
                            Level = "Certificate IV",
                            Location = "Wollongong",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "CREA1",
                            CourseArea = "Creative Arts",
                            CourseName = "Introduction to Fashion Design",
                            Duration = "6 months",
                            EstimatedFee = 3000m,
                            Level = "Certificate II",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "CREA2",
                            CourseArea = "Creative Arts",
                            CourseName = "Interior Design",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA3",
                            CourseArea = "Creative Arts",
                            CourseName = "Photography",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate IV",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA4",
                            CourseArea = "Creative Arts",
                            CourseName = "Fine Arts",
                            Duration = "36 months",
                            EstimatedFee = 28000m,
                            Level = "Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA5",
                            CourseArea = "Creative Arts",
                            CourseName = "Graphic Design",
                            Duration = "9 months",
                            EstimatedFee = 4000m,
                            Level = "Certificate III",
                            Location = "Canberra",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "CREA6",
                            CourseArea = "Creative Arts",
                            CourseName = "Digital Animation and 3D Modelling",
                            Duration = "18 months",
                            EstimatedFee = 12000m,
                            Level = "Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA7",
                            CourseArea = "Creative Arts",
                            CourseName = "Acting and Performance",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate IV",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "CREA8",
                            CourseArea = "Creative Arts",
                            CourseName = "Music Production",
                            Duration = "36 months",
                            EstimatedFee = 28000m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA9",
                            CourseArea = "Creative Arts",
                            CourseName = "Digital Illustration",
                            Duration = "9 months",
                            EstimatedFee = 5000m,
                            Level = "Certificate III",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA10",
                            CourseArea = "Creative Arts",
                            CourseName = "Film and Television Studies",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Diploma",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA11",
                            CourseArea = "Creative Arts",
                            CourseName = "Fine Arts",
                            Duration = "24 months",
                            EstimatedFee = 24000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA12",
                            CourseArea = "Creative Arts",
                            CourseName = "Game Art",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate IV",
                            Location = "Brisbane",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "CREA13",
                            CourseArea = "Creative Arts",
                            CourseName = "Advanced Photography Techniques",
                            Duration = "12 months",
                            EstimatedFee = 7800m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "CREA14",
                            CourseArea = "Creative Arts",
                            CourseName = "Theatre Production and Stage Design",
                            Duration = "18 months",
                            EstimatedFee = 10000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "CREA15",
                            CourseArea = "Creative Arts",
                            CourseName = "Creative Writing",
                            Duration = "9 months",
                            EstimatedFee = 4000m,
                            Level = "Certificate III",
                            Location = "Wollongong",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "BUS101",
                            CourseArea = "Business and Administration",
                            CourseName = "Business Administration Basics",
                            Duration = "6 months",
                            EstimatedFee = 2000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "BUS201",
                            CourseArea = "Business and Administration",
                            CourseName = "Leadership",
                            Duration = "12 months",
                            EstimatedFee = 4500m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "BUS301",
                            CourseArea = "Business and Administration",
                            CourseName = "Commerce",
                            Duration = "36 months",
                            EstimatedFee = 30000m,
                            Level = "Diploma",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS401",
                            CourseArea = "Business and Administration",
                            CourseName = "Graduate Diploma in Project Management",
                            Duration = "12 months",
                            EstimatedFee = 12000m,
                            Level = "Graduate Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS501",
                            CourseArea = "Business and Administration",
                            CourseName = "Business Administration",
                            Duration = "24 months",
                            EstimatedFee = 35000m,
                            Level = "Diploma",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS601",
                            CourseArea = "Business and Administration",
                            CourseName = "Advanced Human Resource Management",
                            Duration = "12 months",
                            EstimatedFee = 12500m,
                            Level = "Graduate Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS602",
                            CourseArea = "Business and Administration",
                            CourseName = "Small Business Management",
                            Duration = "12 months",
                            EstimatedFee = 4800m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "BUS603",
                            CourseArea = "Business and Administration",
                            CourseName = "International Business",
                            Duration = "24 months",
                            EstimatedFee = 33000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS604",
                            CourseArea = "Business and Administration",
                            CourseName = "Graduate Certificate in Logistics and Supply Chain",
                            Duration = "12 months",
                            EstimatedFee = 9500m,
                            Level = "Graduate Certificate",
                            Location = "Brisbane",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "BUS605",
                            CourseArea = "Business and Administration",
                            CourseName = "Marketing and Communications",
                            Duration = "12 months",
                            EstimatedFee = 5200m,
                            Level = "Certificate IV",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS606",
                            CourseArea = "Business and Administration",
                            CourseName = "Accounting",
                            Duration = "36 months",
                            EstimatedFee = 30000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS607",
                            CourseArea = "Business and Administration",
                            CourseName = "E-Commerce",
                            Duration = "18 months",
                            EstimatedFee = 10000m,
                            Level = "Diploma",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS608",
                            CourseArea = "Business and Administration",
                            CourseName = "Business Operations",
                            Duration = "9 months",
                            EstimatedFee = 3500m,
                            Level = "Certificate III",
                            Location = "Brisbane",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "BUS609",
                            CourseArea = "Business and Administration",
                            CourseName = "Graduate Diploma in Finance",
                            Duration = "18 months",
                            EstimatedFee = 12000m,
                            Level = "Graduate Diploma",
                            Location = "Sydney",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "BUS610",
                            CourseArea = "Business and Administration",
                            CourseName = "Master of Entrepreneurship",
                            Duration = "24 months",
                            EstimatedFee = 34000m,
                            Level = "Master",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "BUS611",
                            CourseArea = "Business and Administration",
                            CourseName = "Project Coordination",
                            Duration = "12 months",
                            EstimatedFee = 4700m,
                            Level = "Certificate IV",
                            Location = "Perth",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "BUS612",
                            CourseArea = "Business and Administration",
                            CourseName = "Advanced Diploma in Strategic Leadership",
                            Duration = "18 months",
                            EstimatedFee = 11500m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG01",
                            CourseArea = "Agriculture",
                            CourseName = "Agricultural Practices",
                            Duration = "9 months",
                            EstimatedFee = 4200m,
                            Level = "Certificate III",
                            Location = "Regional NSW",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG02",
                            CourseArea = "Agriculture",
                            CourseName = "Horticulture",
                            Duration = "12 months",
                            EstimatedFee = 5500m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "AG03",
                            CourseArea = "Agriculture",
                            CourseName = "Agribusiness",
                            Duration = "18 months",
                            EstimatedFee = 9000m,
                            Level = "Diploma",
                            Location = "Brisbane",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG04",
                            CourseArea = "Agriculture",
                            CourseName = "Agricultural Science",
                            Duration = "36 months",
                            EstimatedFee = 28000m,
                            Level = "Diploma",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG05",
                            CourseArea = "Agriculture",
                            CourseName = "Sustainable Farming Practices",
                            Duration = "6 months",
                            EstimatedFee = 7000m,
                            Level = "Graduate Certificate",
                            Location = "Sydney",
                            StudyOption = "Self-paced"
                        },
                        new
                        {
                            CourseCode = "AG06",
                            CourseArea = "Agriculture",
                            CourseName = "Rural Operations",
                            Duration = "9 months",
                            EstimatedFee = 3000m,
                            Level = "Certificate II",
                            Location = "Regional NSW",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG07",
                            CourseArea = "Agriculture",
                            CourseName = "Viticulture",
                            Duration = "18 months",
                            EstimatedFee = 8500m,
                            Level = "Diploma",
                            Location = "Adelaide",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "AG08",
                            CourseArea = "Agriculture",
                            CourseName = "Graduate Certificate in Agricultural Economics",
                            Duration = "12 months",
                            EstimatedFee = 9000m,
                            Level = "Graduate Certificate",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG09",
                            CourseArea = "Agriculture",
                            CourseName = "Wool Classing",
                            Duration = "12 months",
                            EstimatedFee = 5500m,
                            Level = "Certificate IV",
                            Location = "Melbourne",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG10",
                            CourseArea = "Agriculture",
                            CourseName = "Animal Science",
                            Duration = "36 months",
                            EstimatedFee = 28000m,
                            Level = "Diploma",
                            Location = "Sydney",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG11",
                            CourseArea = "Agriculture",
                            CourseName = "Organic Farming",
                            Duration = "18 months",
                            EstimatedFee = 9000m,
                            Level = "Diploma",
                            Location = "Regional QLD",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG12",
                            CourseArea = "Agriculture",
                            CourseName = "Graduate Diploma in Crop Science",
                            Duration = "18 months",
                            EstimatedFee = 11000m,
                            Level = "Graduate Diploma",
                            Location = "Brisbane",
                            StudyOption = "Part time"
                        },
                        new
                        {
                            CourseCode = "AG13",
                            CourseArea = "Agriculture",
                            CourseName = "Agricultural Machinery",
                            Duration = "12 months",
                            EstimatedFee = 6000m,
                            Level = "Certificate III",
                            Location = "Adelaide",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG14",
                            CourseArea = "Agriculture",
                            CourseName = "Aquaculture",
                            Duration = "12 months",
                            EstimatedFee = 6500m,
                            Level = "Certificate IV",
                            Location = "Perth",
                            StudyOption = "Full time"
                        },
                        new
                        {
                            CourseCode = "AG15",
                            CourseArea = "Agriculture",
                            CourseName = "Sustainable Agriculture",
                            Duration = "24 months",
                            EstimatedFee = 20000m,
                            Level = "Diploma",
                            Location = "Canberra",
                            StudyOption = "Full time"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
